language: scala
sudo: false
script: sbt -jvm-opts jvmopts.travis +test
jdk:
- oraclejdk8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7e03eb850971919f740b
    on_success: change
    on_failure: always
    on_start: false
after_success:
- ! '[[ $TRAVIS_BRANCH == "develop" ]] && { sbt "+publish" ; };'
env:
  global:
  - secure: VVyIsdj+WEXW6jwW7PxbGmlMmUYpy/qjH6vCvYgHK7Rrz/cX4GuT1FXE9xLnAZua2tWejkfBCSy+DPxAnDsVugAa0cvfHgA+i13/Zbm7LkH2PPvnIdjgl9LlhhxAHFr/OL8dKthPWw1U7wkFhCgFxN/OGytya0TItMOYiBG2cvk=
  - secure: QdGIhfPlMVPFR8e9REJwDLKbKwcleOTY5c+foJzLtyW3Y3yXt0jOzqdBUZqEMyTjvYDPcwabL6IMVp6vir3cIYLIxQx9eFofzAnwUfSOzJ7ASxdkPD5LZJXQHzHN+alskbyPF7y28kAuJEFF+FPlkH+3rSr7eBew3NAJqqUlpzI=
